// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const getUserScratchcardsByScratchId = `-- name: GetUserScratchcardsByScratchId :one
SELECT id, sc_id, user_id, status FROM user_scratchcards
WHERE sc_id = $1 LIMIT 1
`

func (q *Queries) GetUserScratchcardsByScratchId(ctx context.Context, scID uuid.UUID) (UserScratchcard, error) {
	row := q.db.QueryRowContext(ctx, getUserScratchcardsByScratchId, scID)
	var i UserScratchcard
	err := row.Scan(
		&i.ID,
		&i.ScID,
		&i.UserID,
		&i.Status,
	)
	return i, err
}
